Create word_search.py
ReemaJiries/CodeU pull request #3
Opened 2017-06-11 23:41 UTC by ReemaJiries

Assignment 3

2017-06-18 10:11 UTC, ariava approved these changes
Well done! I think your code is well tested and well documented.

2017-06-18 10:11 UTC, ariava commented on word_search.py
> +    """
Please put the docstring just after the definition of the method, e.g.:

def isPrefix(self, prefix):
"""
<docstring>
"""
...

2017-06-18 10:11 UTC, ariava commented on word_search.py
> +    helper function filles valid_words according to te given inputs
Nit: te -> the

2017-06-18 10:11 UTC, ariava commented on word_search.py
> +    and the dictionary
Is this a stray line? Or does it go with the previous line?

2017-06-18 10:11 UTC, ariava commented on word_search.py
> +
Did you want to add some more testing here?

2017-06-18 15:11 UTC, OlgaVorokh requested changes
Can you please fix my comments, and than I will look though your code once again and maybe add new comments for improving your code?

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
>  def find_words_prefix(charecter,i,j,num_of_rows, num_of_columns, grid, dictionary,isVisit,valid_words ):
According to pep8, you should put space after comma and before new variable name and not  to put it before closing bracket. So it should be in that way:
`def function_name(arg1, arg2, arg3):`

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
>                  find_words_prefix(w,x,y,num_of_rows, num_of_columns, grid, dictionary, isVisit,valid_words)
The same problem as I described before. Pep8

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +if __name__ == '__main__':
According to pep8, you need to put two empty lines between classes and functions, between `if __name__ == '__main__'` and some staff too.

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +    print("Testing valid inputs:")
Maybe try to use some python libraries for testing, for example, `unittest`, your code will be prettier and easier to understand. And things such as `print("Done\n")` would be printed by the library

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +    class Dictionary:
It will be better in this case to move this class from main module. Yes, there are some cases in coding life, when you can implement some class inside methods and functions because this classes have local usage, but in this case this class is a part of problem solution and it should be global.

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +        def isWord(self, word):
According to pep 8, you should put only one empty line between methods in classes.

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +            self.k = pa
It is very bad code style, when you name your attributes, variables, function names and so on very short. For other programmers that should work with your code in future, your code should be clear and easy to understand. Names of variables should show their meaning, logic why you created it, name of functions should show what happening and function and so on.

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +            for i in range(len(self.k)):
This method should be implemented in more pythonic way:
```
def isWord(self, word):
    return word in self.k
```

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +            for i in range(len(self.p)):
You should change this method in the way like I changed your `isWord` method

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +    if (len(grid) < num_of_rows):
Remove redundant parentheses

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +        if (len(grid[i]) < num_of_columns):
Remove redundant parentheses

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +            if (dictionary.isPrefix(charecter)):
Remove redundant parentheses

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +                for r in range(num_of_rows):
You just can recreate your `isVisit` variable

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +                if(dictionary.isWord(w)):
You twice add one word in your set. Because of set it is not so bad, but nevertheless you can delete this` if` case

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +    x = max(0, i-1)
This is not used

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +    if(dictionary.isWord(charecter)):
Remove redundant parentheses everywhere in cases like that

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +            if((x != i or y != j) and (isVisit[x][y] == False) and (dictionary.isPrefix(w))):
`isVisit[x][y] == False` => `not isVisit[x][y]`
and just for your information
`lalala == True` => `lalala`

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +            if((x != i or y != j) and (isVisit[x][y] == False) and (dictionary.isPrefix(w))):
The first condition you can remove from `if` because if the first condition is True, the second one also True

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +def word_search(num_of_rows = 0, num_of_columns = 0, grid = [], dictionary = {}):
You can get `num_of_rows` and `num_of_columns` from `grid` and not pass as argument to function.

2017-06-18 15:11 UTC, OlgaVorokh commented on word_search.py
> +            self.k = pa
You should calculate prefixes in some method class , not by yourself.
And you contain your information in lists, but it's would be asymptotically better to use set

2017-06-18 15:45 UTC, ReemaJiries commented on word_search.py
> +
thank you I fixed it

2017-06-18 15:46 UTC, ReemaJiries commented on word_search.py
> +            for i in range(len(self.p)):
thank you Olga, I will fix it as soon as possible

2017-06-23 14:23 UTC, ReemaJiries commented on word_search.py
> +    print("Testing valid inputs:")
I will take it into account next time next time

2017-06-23 14:32 UTC, ReemaJiries commented on word_search.py
> +def word_search(num_of_rows = 0, num_of_columns = 0, grid = [], dictionary = {}):
it is okay also to passing it

2017-07-09 21:23 UTC, OlgaVorokh approved these changes
You haven't changed any of my notes about code structure, but this solution is working. So I approved this version of code. I hope that my comments will be useful for you in your future work!

2017-07-13 21:12 UTC, merged