Create rearranging_cars.py
ReemaJiries/CodeU pull request #6
Opened 2017-07-19 22:03 UTC by ReemaJiries

Assignment 6

2017-07-19 22:34 UTC, joanna- commented on rearranging_cars.py
> +
Here I think we should again check if the move is required. Please consider this example:
rearranging_cars([3, 1, 2, 0], [0, 1, 2, 3])
In this case we need only one move from 0 to 3 in order to get arrangement. However, your solution gives the answer:
[(0, 3), (3, 0)].

2017-07-19 22:38 UTC, joanna- requested changes
I think the code is simple and clean, easy to read. Good job! :) 

I pointed out one corner case in which your solution is failing though.

2017-07-20 16:47 UTC, ReemaJiries commented on rearranging_cars.py
> +
Thank You for the review, I have correct it. I have to add more tests but I have exams right now so I will add it later.

2017-07-21 19:34 UTC, joanna- approved these changes

2017-07-21 19:35 UTC, joanna- commented on rearranging_cars.py
> +
Thank you for the fix. Fingers crossed for your exams! :)

2017-07-25 08:36 UTC, galeal2 reviewed
Very nice! 😉

2017-07-25 16:18 UTC, yuvdanilova approved these changes
Your code is good!

I personally found it a bit hard visually as you prefer to longer variable names (it's great as it's understandable) and yet keep it all in one function. Maybe if you could split the code or, for example, shorten 'position' to 'pos', it would be a bit easier to read.

Though these are very minor issues and overall it's cool 👍

2017-07-25 17:00 UTC, yuvdanilova commented on rearranging_cars.py
> +
```
    final_arrangement = []
    for i in range(len(old_parking)):
        final_arrangement.append(map_slot_cars[i])
    return final_arrangement
```

If I add this code here, should it return the right arrangement?
If yes, it fails on this input:

init: [6, 10, 2, 3, 8, 4, 5, 7, 1, 0, 9]
suggested output: [2, 1, 10, 8, 7, 3, 6, 9, 0, 4, 5]
actual output: [8, 1, 0, 5, 9, 10, 6, 4, 3, 7, 2]

2017-07-25 17:09 UTC, ReemaJiries commented on rearranging_cars.py
> +
You can just print(old_parking) and it's will output the actual output correctly, I have tried it and it passed

2017-07-31 09:39 UTC, ariava approved these changes
Good job. When you have time please add a top-level comment explaining the general strategy you applied to develop your solution.

2017-08-05 12:23 UTC, merged